spring:
  mail:
    host: smtp.gmail.com
    password: <Enter Your App password not Email Password>
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: <Enter Your Email>
